import type { Metadata } from "next"

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"

export async function generateMetadata({ params }: { params: { id: string } }): Promise<Metadata> {
  try {
    const res = await fetch(`${API}/manga/${params.id}`, { cache: "no-store" })
    if (!res.ok) return { title: "Emaki — Turn anyone into a manga" }
    const manga = await res.json()
    const name = manga.title || manga.subject_name || "A Manga Story"
    const coverImg = manga.pages?.find((p: any) => p.type === "img")?.image_url
    return {
      title: `${name} — Emaki`,
      description: manga.tagline || "A manga about someone's life, generated by Emaki.",
      openGraph: {
        title: name,
        description: manga.tagline || "",
        images: coverImg ? [{ url: coverImg }] : [],
        type: "article",
      },
      twitter: {
        card: "summary_large_image",
        title: name,
        description: manga.tagline || "",
        images: coverImg ? [coverImg] : [],
      },
    }
  } catch {
    return { title: "Emaki — Turn anyone into a manga" }
  }
}

export default function MangaLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
