import type { Metadata } from "next"

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"

export async function generateMetadata({ params }: { params: { id: string } }): Promise<Metadata> {
  try {
    const res = await fetch(`${API}/manga/${params.id}`, { next: { revalidate: 60 } })
    const manga = await res.json()
    const coverImg = manga.pages?.find((p: any) => p.type === "img")?.image_url
    return {
      title: `${manga.title || manga.subject_name} — Emaki`,
      description: manga.tagline || "A manga about someone's life, generated by Emaki.",
      openGraph: {
        title: manga.title || manga.subject_name,
        description: manga.tagline || "",
        images: coverImg ? [{ url: coverImg }] : [],
        type: "article",
      },
      twitter: {
        card: "summary_large_image",
        title: manga.title || manga.subject_name,
        description: manga.tagline || "",
        images: coverImg ? [coverImg] : [],
      },
    }
  } catch {
    return { title: "Emaki — Turn anyone into a manga" }
  }
}

export default function MangaLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>
}
